### ISSUE TITLE
dynamic rules not working

### ISSUE THREAD

**Issue by anton1konon** [DATAHOARDERS/dynamic-rules#251]
is there any update? thanks

**Comment by isnifer** [comment]
I have the same issue here

**Comment by isnifer** [comment]
@UltimaHoarder it's your time, bro)

**Comment by bytadaniel** [comment]
Same thing, guys. Falling into "Please refresh the page" error.

**Comment by bytadaniel** [comment]
Has anybody any type of comprehension about how to derive this dynamic rules?

**Comment by Tg00174** [comment]
anyone have solution ?

**Comment by anton1konon** [comment]
@Tg00174 
@isnifer 
curently using this one: 
https://raw.githubusercontent.com/riley-access-labs/onlyfans-dynamic-rules-1/patch-1/dynamicRules.json
@bytadaniel also found this repository: https://github.com/xagler/dynamic-rules

**Comment by gangster665** [comment]
@anton1konon this doesn't work anymore. Any updates pls?

**Comment by gangster665** [comment]
@anton1konon
@isnifer
@bytadaniel
@Tg00174
guys i found working dynamic rules here
https://github.com/Growik/onlyfans-dynamic-rules/blob/main/rules.json
also repo seems to be constantly updated

**Comment by datkoa25** [comment]
Auth (V1) Attempt 1/10
Traceback (most recent call last):
  File "D:\Github\start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "D:\Github\start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "D:\Github\datascraper\main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "D:\Github\datascraper\main_datascraper.py", line 74, in default
    setup, subscriptions = await account_setup(
  File "D:\Github\helpers\main_helper.py", line 983, in account_setup
    authed = await auth.login()
  File "D:\Github\apis\onlyfans\classes\auth_model.py", line 109, in login
    await self.process_auth()
  File "D:\Github\apis\onlyfans\classes\auth_model.py", line 169, in process_auth
    response = await self.session_manager.json_request(link)
  File "D:\Github\apis\api_helper.py", line 172, in json_request
    headers = self.session_rules(link)
  File "D:\Github\apis\api_helper.py", line 334, in session_rules
    headers["app-token"] = dynamic_rules["app_token"]
KeyError: 'app_token'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001AD85CFA5F0>

**Comment by gangster665** [comment]
@datkoa25 you should try 'app-token' instead of 'app_token'

**Comment by xagler** [comment]
@anton1konon
@isnifer
@bytadaniel
@Tg00174
@gangster665 
guys i found
you can use my repo https://github.com/xagler/dynamic-rules

**Comment by datkoa25** [comment]
@xagler 
"Please refresh the page" error. :(((

**Comment by xagler** [comment]
> @xagler "Please refresh the page" error. :(((

thats not true, just checked

**Comment by datkoa25** [comment]
https://imgur.com/a/7XXktG4
